title: Chong Zhao
description: Chong Zhao's blog.
author: Chong Zhao
avatar: /logo.png
email: 1819628216@qq.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.png
social:
  name: Chong Zhao
  links:
    - https://github.com/nobelheaven
# google_site_verification:
lang: en
